# Generated by Django 2.1.7 on 2019-04-04 08:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, unique=True)),
                ('start_life', models.DateField(default=datetime.date.today, null=True)),
                ('expire_date', models.DateField(default=datetime.date.today, null=True)),
                ('start_quiet_hour', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('end_quiet_hour', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('room_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
