# Generated by Django 2.1.7 on 2019-03-24 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='end_quiet_hour',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='channel',
            name='expire_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='start_quiet_hour',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
