# Generated by Django 2.1.7 on 2019-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_channel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(null=True)),
                ('member_id', models.IntegerField(null=True)),
            ],
        ),
    ]
