# Generated by Django 2.1.5 on 2019-03-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190324_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_owner',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
