# Generated by Django 2.1.7 on 2019-05-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_channelmembers'),
        ('main', '0003_ticket'),
    ]

    operations = [
    ]
