# Generated by Django 2.1.5 on 2019-03-27 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_channel_channel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
