# Generated by Django 2.1.7 on 2019-05-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticket'),
        ('main', '0003_messages'),
    ]

    operations = [
    ]
