# Generated by Django 2.1.5 on 2019-03-27 05:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190327_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_owner',
            field=models.CharField(max_length=40, verbose_name=django.contrib.auth.models.User),
        ),
    ]
