# Generated by Django 2.1.7 on 2019-05-07 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20190506_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='end_quiet_hour',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='channel',
            name='start_quiet_hour',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
