# Generated by Django 2.1.5 on 2019-03-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190327_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_name',
            new_name='room_name',
        ),
    ]
