# Generated by Django 2.1.7 on 2019-05-07 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190506_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='end_quiet_hour',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='channel',
            name='start_quiet_hour',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
