# Generated by Django 2.1.5 on 2019-05-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20190503_2236'),
        ('main', '0006_auto_20190506_2354'),
    ]

    operations = [
    ]
