# Generated by Django 2.1.5 on 2019-03-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190328_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_owner',
        ),
        migrations.AddField(
            model_name='channel',
            name='room_owner',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
