# Generated by Django 2.1.7 on 2019-03-31 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190330_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='start_life',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='expire_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
